//! Provider CI templates. Pure string generation: deterministic, no credentials.
//!
//! Every generated pipeline installs a pinned `@entwine/cli` release. To use a different
//! install source (for example a release binary), edit the single install line.

pub(crate) const MARKER: &str = "entwine-managed";
const HEADER: &str = "# entwine-managed: generated by `entwine setup`. Safe to edit.\n# Delete this file and re-run `entwine setup` to regenerate it.\n";

/// Where the project lives inside the repository. Empty for the repository root.
#[derive(Debug, Clone, Default)]
pub(crate) struct Layout {
    /// Repository-relative project directory with a trailing slash, or empty.
    pub prefix: String,
}
impl Layout {
    fn project_arg(&self) -> String {
        if self.prefix.is_empty() {
            String::new()
        } else {
            format!(" {}", self.prefix.trim_end_matches('/'))
        }
    }
}

pub(crate) const GITHUB_PATH: &str = ".github/workflows/entwine.yml";
pub(crate) const GITLAB_PATH: &str = ".gitlab/ci/entwine.yml";
pub(crate) const GITLAB_ROOT: &str = ".gitlab-ci.yml";
pub(crate) const BITBUCKET_PATH: &str = "bitbucket-pipelines.yml";
pub(crate) const BITBUCKET_SNIPPET: &str = ".entwine/bitbucket-pipelines.snippet.yml";

fn fill(template: &str, version: &str, layout: &Layout, extra: &[(&str, &str)]) -> String {
    let mut text = template
        .replace("__VERSION__", version)
        .replace("__PREFIX__", &layout.prefix)
        .replace("__PROJECT__", &layout.project_arg());
    for (key, value) in extra {
        text = text.replace(key, value);
    }
    text
}

pub(crate) fn github(version: &str, layout: &Layout) -> String {
    let body = r#"name: Entwine docs

on:
  pull_request:
    paths:
      - "__PREFIX__docs/**"
      # Repository references may change anywhere in the work tree.
      - "**"
      - ".github/workflows/entwine.yml"
  push:
    paths:
      - "__PREFIX__docs/**"
      # Repository references may change anywhere in the work tree.
      - "**"
      - ".github/workflows/entwine.yml"
  workflow_dispatch:

# Least privilege: the deploy job alone receives Pages and OIDC permissions.
permissions:
  contents: read

env:
  ENTWINE_VERSION: "__VERSION__"

jobs:
  build:
    # Pull requests are validated; only the default branch is built for publishing.
    if: github.event_name == 'pull_request' || github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Install Entwine
        run: npm install --global "@entwine/cli@${ENTWINE_VERSION}"
      - name: Validate documentation
        run: entwine check__PROJECT__
      - name: Build static site
        if: github.event_name != 'pull_request'
        run: entwine build__PROJECT__
      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v5
        with:
          path: __PREFIX__dist

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
"#;
    format!("{HEADER}{}", fill(body, version, layout, &[]))
}

pub(crate) fn gitlab(version: &str, layout: &Layout) -> String {
    let body = r#".entwine-base:
  image: $ENTWINE_IMAGE
  variables:
    ENTWINE_IMAGE: "node:22"
    ENTWINE_VERSION: "__VERSION__"

# Merge requests: validate only.
entwine:check:
  extends: .entwine-base
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - __PREFIX__docs/**/*
        - "**/*" # Repository references may change outside docs/.
        - .gitlab/ci/entwine.yml
  script:
    - npm install --global "@entwine/cli@${ENTWINE_VERSION}"
    - entwine check__PROJECT__

# Default branch: validate and build once; the Pages job publishes this exact artifact.
entwine:build:
  extends: .entwine-base
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - __PREFIX__docs/**/*
        - "**/*" # Repository references may change outside docs/.
        - .gitlab/ci/entwine.yml
  script:
    - npm install --global "@entwine/cli@${ENTWINE_VERSION}"
    - entwine check__PROJECT__
    - entwine build__PROJECT__
  artifacts:
    paths:
      - __PREFIX__dist
    expire_in: 1 day

# `pages.publish` requires GitLab 17.10 or later (GitLab.com and Self-Managed).
entwine:pages:
  extends: .entwine-base
  stage: deploy
  needs:
    - entwine:build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - __PREFIX__docs/**/*
        - "**/*" # Repository references may change outside docs/.
        - .gitlab/ci/entwine.yml
  script:
    - echo "Publishing the Entwine build validated in entwine:build"
  pages:
    publish: __PREFIX__dist
"#;
    format!("{HEADER}{}", fill(body, version, layout, &[]))
}

/// The root `.gitlab-ci.yml` content when none exists, or the block to prepend.
pub(crate) fn gitlab_include() -> String {
    format!("{HEADER}include:\n  - local: {GITLAB_PATH}\n")
}

pub(crate) fn bitbucket(version: &str, layout: &Layout, default_branch: &str) -> String {
    let body = r#"pipelines:
  pull-requests:
    "**":
      - step:
          name: Validate Entwine documentation
          image: node:22
          condition:
            changesets:
              includePaths:
                - "__PREFIX__docs/**"
                - "**" # Repository references may change outside docs/.
          script:
            - npm install --global "@entwine/cli@__VERSION__"
            - entwine check__PROJECT__
  branches:
    "__BRANCH__":
      - step:
          name: Build and publish Entwine documentation
          image: node:22
          condition:
            changesets:
              includePaths:
                - "__PREFIX__docs/**"
                - "**" # Repository references may change outside docs/.
          script:
            - npm install --global "@entwine/cli@__VERSION__"
            - entwine check__PROJECT__
            - entwine build__PROJECT__
            # One-time setup: a repository named <workspace>.bitbucket.io and a secured
            # repository variable ENTWINE_SITE_TOKEN (a write-scoped access token for it).
            - |
              set -eu
              if [ -z "${ENTWINE_SITE_TOKEN:-}" ]; then
                echo "ENTWINE_SITE_TOKEN is not set. See the Entwine deployment documentation." >&2
                exit 1
              fi
              # Provider variables are data, never executable shell or path traversal.
              for value in "$BITBUCKET_WORKSPACE" "$BITBUCKET_REPO_SLUG"; do
                case "$value" in
                  ""|*[!a-zA-Z0-9_-]*|-*) echo "Invalid Bitbucket workspace or repository slug" >&2; exit 1 ;;
                esac
              done
              DIST="$BITBUCKET_CLONE_DIR/__PREFIX__dist"
              SITE="$HOME/entwine-site"
              ASKPASS="$HOME/entwine-askpass.sh"
              printf '#!/bin/sh\ncase "$1" in Username*) echo x-token-auth ;; *) echo "$ENTWINE_SITE_TOKEN" ;; esac\n' > "$ASKPASS"
              chmod 700 "$ASKPASS"
              trap 'rm -f "$ASKPASS"' EXIT
              export GIT_ASKPASS="$ASKPASS" GIT_TERMINAL_PROMPT=0
              git clone --depth 1 "https://bitbucket.org/${BITBUCKET_WORKSPACE}/${BITBUCKET_WORKSPACE}.bitbucket.io.git" "$SITE"
              rm -rf "$SITE/$BITBUCKET_REPO_SLUG"
              mkdir -p "$SITE/$BITBUCKET_REPO_SLUG"
              cp -R "$DIST/." "$SITE/$BITBUCKET_REPO_SLUG/"
              rm -f "$SITE/$BITBUCKET_REPO_SLUG/.entwine-output"
              cd "$SITE"
              git add -A "$BITBUCKET_REPO_SLUG"
              if git diff --cached --quiet; then
                echo "No documentation changes to publish."
                exit 0
              fi
              git -c user.name="Entwine pipeline" -c user.email="entwine@users.noreply.bitbucket.org" commit -q -m "Publish $BITBUCKET_REPO_SLUG documentation ($BITBUCKET_COMMIT)"
              git push -q origin HEAD
"#;
    format!(
        "{HEADER}{}",
        fill(body, version, layout, &[("__BRANCH__", default_branch)])
    )
}
