use crate::resolve::relative_url;
use entwine_core::*;
use std::collections::BTreeMap;

/// A file ready for a caller-controlled output directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StaticFile {
    pub path: String,
    pub contents: Vec<u8>,
}

pub(crate) fn escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
fn frame(title: &str, route: &str, content: &str) -> String {
    format!("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"generator\" content=\"Entwine 0.1.0\"><title>{}</title><link rel=\"stylesheet\" href=\"{}\"></head><body><a class=\"skip\" href=\"#main\">Skip to content</a>{content}</body></html>", escape(title), escape(&relative_url(route, "/__entwine/style.css")))
}
fn nav(items: &[Navigation], current: &Route) -> String {
    let mut html = String::from("<ul>");
    for item in items {
        html.push_str("<li>");
        if let Some(route) = &item.route {
            html.push_str(&format!(
                "<a href=\"{}\"{}>{}</a>",
                escape(&relative_url(current.as_str(), route.as_str())),
                if route == current {
                    " aria-current=\"page\""
                } else {
                    ""
                },
                escape(&item.label)
            ));
        } else {
            html.push_str(&format!(
                "<span class=\"group\">{}</span>",
                escape(&item.label)
            ));
        }
        if !item.children.is_empty() {
            html.push_str(&nav(&item.children, current));
        }
        html.push_str("</li>");
    }
    html.push_str("</ul>");
    html
}

/// Render the site exclusively from its projection, without parsing Markdown.
pub fn render_site(site: &SiteModel) -> Vec<StaticFile> {
    let mut files = vec![StaticFile {
        path: "__entwine/style.css".into(),
        contents: include_bytes!("style.css").to_vec(),
    }];
    for page in &site.pages {
        let toc = page
            .headings
            .iter()
            .map(|h| {
                format!(
                    "<li class=\"level-{}\"><a href=\"#{}\">{}</a></li>",
                    h.level,
                    escape(&h.id),
                    escape(&h.text)
                )
            })
            .collect::<String>();
        let backlinks = if page.backlinks.is_empty() {
            String::new()
        } else {
            format!("<section class=\"backlinks\" aria-label=\"Referenced by\"><h2>Referenced by</h2><ul>{}</ul></section>", page.backlinks.iter().map(|b| format!("<li><a href=\"{}\">{}</a></li>", escape(&relative_url(page.route.as_str(), b.route.as_str())), escape(&b.title))).collect::<String>())
        };
        let metadata = [&page.metadata.kind, &page.metadata.status]
            .into_iter()
            .flatten()
            .map(|value| format!("<span>{}</span>", escape(value)))
            .collect::<String>();
        let title = if page
            .headings
            .first()
            .is_some_and(|heading| heading.level == 1 && heading.text == page.title)
        {
            String::new()
        } else {
            format!("<h1>{}</h1>", escape(&page.title))
        };
        let content = format!("<header class=\"mobile\">Entwine documentation</header><div class=\"layout\"><aside class=\"sidebar\"><p class=\"brand\">Entwine</p><nav aria-label=\"Documentation\">{}</nav><a class=\"graph-link\" href=\"{}\">Project graph</a></aside><main id=\"main\"><header><p class=\"metadata\">{metadata}</p>{title}</header><article>{}</article>{backlinks}<footer>Generated by Entwine · Markdown remains the source of truth.</footer></main><aside class=\"toc\"><nav aria-label=\"On this page\"><h2>On this page</h2><ul>{toc}</ul></nav></aside></div>", nav(&site.navigation, &page.route), escape(&relative_url(page.route.as_str(), &site.graph_route)), page.html);
        files.push(StaticFile {
            path: format!("{}index.html", page.route.as_str().trim_start_matches('/')),
            contents: frame(&page.title, page.route.as_str(), &content).into_bytes(),
        });
    }
    files
}

/// Deterministic SVG with linked nodes, directional edges, and a readable edge list.
pub fn render_graph(graph: &GraphModel) -> StaticFile {
    let route = "/__entwine/graph/";
    let height = graph.nodes.len().max(1) * 90 + 30;
    let positions: BTreeMap<_, _> = graph
        .nodes
        .iter()
        .enumerate()
        .map(|(i, node)| (node.id.clone(), 50 + i * 90))
        .collect();
    let mut svg = format!("<svg class=\"graph\" xmlns=\"http://www.w3.org/2000/svg\" width=\"850\" height=\"{height}\" viewBox=\"0 0 850 {height}\" role=\"img\" aria-labelledby=\"graph-title graph-description\"><title id=\"graph-title\">Project knowledge graph</title><desc id=\"graph-description\">{} documents, {} directed references. A text list of all relationships follows.</desc><defs><marker id=\"arrow\" viewBox=\"0 0 10 10\" refX=\"9\" refY=\"5\" markerWidth=\"6\" markerHeight=\"6\" orient=\"auto-start-reverse\"><path d=\"M 0 0 L 10 5 L 0 10 z\"/></marker></defs>", graph.nodes.len(), graph.edges.len());
    for (i, edge) in graph.edges.iter().enumerate() {
        if let (Some(source), Some(target)) =
            (positions.get(&edge.source), positions.get(&edge.target))
        {
            let lane = 440 + (i % 12) * 30;
            let (start, end) = if source == target {
                (source - 12, target + 12)
            } else {
                (*source, *target)
            };
            svg.push_str(&format!("<path class=\"edge\" data-source=\"{}\" data-target=\"{}\" d=\"M 350 {start} C {lane} {start}, {lane} {end}, 350 {end}\" marker-end=\"url(#arrow)\"><title>{} references {}</title></path>", escape(&edge.source.0), escape(&edge.target.0), escape(&edge.source.0), escape(&edge.target.0)));
        }
    }
    for node in &graph.nodes {
        if let Some(y) = positions.get(&node.id) {
            let label: String = node.label.chars().take(34).collect();
            let label = if node.label.chars().count() > 34 {
                format!("{label}…")
            } else {
                label
            };
            svg.push_str(&format!("<a href=\"{}\" data-node=\"{}\" aria-label=\"{}\"><title>{}</title><rect class=\"node\" x=\"20\" y=\"{}\" width=\"330\" height=\"56\" rx=\"8\"/><text x=\"36\" y=\"{}\">{}</text></a>", escape(&relative_url(route, node.route.as_str())), escape(&node.id.0), escape(&node.label), escape(&node.label), y - 28, y + 6, escape(&label)));
        }
    }
    svg.push_str("</svg>");
    let references = graph
        .edges
        .iter()
        .filter_map(|edge| {
            let source = graph.nodes.iter().find(|n| n.id == edge.source)?;
            let target = graph.nodes.iter().find(|n| n.id == edge.target)?;
            Some(format!(
                "<li><a href=\"{}\">{}</a> references <a href=\"{}\">{}</a></li>",
                escape(&relative_url(route, source.route.as_str())),
                escape(&source.label),
                escape(&relative_url(route, target.route.as_str())),
                escape(&target.label)
            ))
        })
        .collect::<String>();
    let nodes = graph
        .nodes
        .iter()
        .map(|n| {
            format!(
                "<li><a href=\"{}\">{}</a></li>",
                escape(&relative_url(route, n.route.as_str())),
                escape(&n.label)
            )
        })
        .collect::<String>();
    let content = format!("<main id=\"main\" class=\"graph-page\"><a href=\"../../\">Documentation</a><h1>Project graph</h1><p>{} documents · {} relationships. Arrows point to referenced documents.</p><div class=\"graph-scroll\">{svg}</div><h2>Documents</h2><ul>{nodes}</ul><h2>Relationships</h2><ul>{references}</ul></main>", graph.nodes.len(), graph.edges.len());
    StaticFile {
        path: "__entwine/graph/index.html".into(),
        contents: frame("Project graph", route, &content).into_bytes(),
    }
}
